import os
import re
import json
import unicodedata
import oracledb
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

# ─────────────────────────────────────────────
# CONFIGURACIÓN ORACLE
# ─────────────────────────────────────────────
ORACLE_USER = os.getenv("ORACLE_USER")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
ORACLE_DSN = os.getenv("ORACLE_DSN") # Ejemplo: localhost:1521/xe

def conectar():
    return oracledb.connect(
        user=ORACLE_USER,
        password=ORACLE_PASSWORD,
        dsn=ORACLE_DSN
    )

def proteger_nombre_oracle(nombre):
    """Encapsula nombres en comillas dobles y mayúsculas para Oracle."""
    return f'"{nombre.upper()}"'

# ─────────────────────────────────────────────
# INICIALIZACIÓN
# ─────────────────────────────────────────────

def inicializar_bbdd():
    conexion = conectar()
    cursor = conexion.cursor()

    # Tablas base del sistema
    tablas = {
        "DOCUMENTOS": """
                      CREATE TABLE documentos (
                                                  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  nombre_archivo VARCHAR2(255),
                                                  tipo_seguro VARCHAR2(100),
                                                  texto_extraido CLOB,
                                                  json_claude CLOB,
                                                  fecha_importacion TIMESTAMP
                      )""",
        "TABLAS_GENERADAS": """
                            CREATE TABLE tablas_generadas (
                                                              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                              id_documento NUMBER,
                                                              nombre_logico VARCHAR2(150),
                                                              nombre_oracle VARCHAR2(150),
                                                              filas_insertadas NUMBER,
                                                              fecha_creacion TIMESTAMP,
                                                              CONSTRAINT fk_doc FOREIGN KEY (id_documento) REFERENCES documentos(id) ON DELETE CASCADE
                            )""",
        "ERRORES_IMPORTACION": """
                               CREATE TABLE errores_importacion (
                                                                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                                    id_documento NUMBER NULL,
                                                                    mensaje_error CLOB,
                                                                    fecha TIMESTAMP
                               )"""
    }

    for nombre, ddl in tablas.items():
        try:
            cursor.execute(ddl)
        except oracledb.DatabaseError as e:
            error, = e.args
            if error.code != 955: # ORA-00955: ya existe el nombre
                raise

    conexion.commit()
    cursor.close()
    conexion.close()

# ─────────────────────────────────────────────
# GESTIÓN DE DOCUMENTOS
# ─────────────────────────────────────────────

def guardar_documento(nombre_archivo, tipo_seguro, texto_extraido, datos_claude):
    conexion = conectar()
    cursor = conexion.cursor()

    id_var = cursor.var(int)
    sql = """
          INSERT INTO documentos (nombre_archivo, tipo_seguro, texto_extraido, json_claude, fecha_importacion)
          VALUES (:1, :2, :3, :4, :5)
              RETURNING id INTO :6 \
          """

    cursor.execute(sql, (
        nombre_archivo,
        tipo_seguro,
        texto_extraido,
        json.dumps(datos_claude, ensure_ascii=False),
        datetime.now(),
        id_var
    ))

    id_doc = id_var.getvalue()[0]
    conexion.commit()
    cursor.close()
    conexion.close()
    return id_doc

# ─────────────────────────────────────────────
# LÓGICA DINÁMICA (LA QUE DABA EL ERROR)
# ─────────────────────────────────────────────

def normalizar_nombre(texto, prefijo):
    if texto is None: texto = "campo"
    texto = str(texto).strip().upper()
    texto = unicodedata.normalize("NFKD", texto).encode("ascii", "ignore").decode("ascii")
    texto = re.sub(r"[^A-Z0-9_]+", "_", texto)
    return texto[:30] # Límite estándar Oracle

def crear_tablas_desde_json_claude(id_documento, datos_claude):
    """
    Procesa el JSON de Claude y crea las tablas necesarias en Oracle.
    Diferencia las tablas por empresa y tipo de seguro para evitar mezclar esquemas.
    """
    tablas = datos_claude.get("tablas", {})

    # Extraemos la compañía y el tipo para el prefijo de la tabla
    # Intentamos buscar 'compañia' en el análisis, si no, usamos el tipo de seguro
    compania = datos_claude.get("analisis", {}).get("compañia", "GEN")
    tipo_seguro = datos_claude.get("tipo_seguro", "AUTO")

    conexion = conectar()
    cursor = conexion.cursor()

    try:
        for nombre_logico, contenido in tablas.items():
            # 1. Generar nombre físico único: S_OCCIDENT_AUTO_TOMADOR
            # Limitamos prefijos para no exceder los 30 caracteres de Oracle
            prefijo_empresa = normalizar_nombre(compania, "")[:8]
            prefijo_tipo = normalizar_nombre(tipo_seguro, "")[:5]
            entidad = normalizar_nombre(nombre_logico, "")

            nombre_fisico = f"S_{prefijo_empresa}_{prefijo_tipo}_{entidad}"[:30]

            # 2. Crear tabla si no existe
            # Se simplifica la FK para que Oracle asigne el nombre automáticamente y no choque
            try:
                cursor.execute(f"""
                    CREATE TABLE {proteger_nombre_oracle(nombre_fisico)} (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        id_documento NUMBER REFERENCES documentos(id) ON DELETE CASCADE,
                        fecha_importacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)
            except oracledb.DatabaseError as e:
                if e.args[0].code != 955: # ORA-00955: name is already used by an existing object
                    raise

            # 3. Normalizar contenido (asegurar que sea una lista de filas)
            filas = contenido if isinstance(contenido, list) else [contenido]

            # 4. Sincronizar columnas dinámicamente
            cursor.execute("SELECT column_name FROM user_tab_columns WHERE table_name = :1", [nombre_fisico.upper()])
            existentes = {fila[0] for fila in cursor.fetchall()}

            for fila in filas:
                if not isinstance(fila, dict): continue
                for col_nombre in fila.keys():
                    col_norm = normalizar_nombre(col_nombre, "C")
                    if col_norm not in existentes:
                        # Usamos CLOB para máxima flexibilidad con textos largos de pólizas
                        cursor.execute(f"ALTER TABLE {proteger_nombre_oracle(nombre_fisico)} ADD ({proteger_nombre_oracle(col_norm)} CLOB)")
                        existentes.add(col_norm)

            # 5. Insertar los datos reales
            for fila in filas:
                if not isinstance(fila, dict): continue

                cols = ["id_documento"]
                vals = [id_documento]

                for k, v in fila.items():
                    cols.append(normalizar_nombre(k, "C"))
                    # Convertimos a JSON string si es una estructura compleja, si no a string simple
                    valor_final = json.dumps(v, ensure_ascii=False) if isinstance(v, (dict, list)) else str(v)
                    vals.append(valor_final)

                columnas_sql = ", ".join(proteger_nombre_oracle(c) for c in cols)
                placeholders = ", ".join([f":{i+1}" for i in range(len(vals))])

                cursor.execute(f"INSERT INTO {proteger_nombre_oracle(nombre_fisico)} ({columnas_sql}) VALUES ({placeholders})", vals)

        conexion.commit()
        print(f"✓ Procesadas {len(tablas)} entidades para el documento ID {id_documento}")

    except Exception as e:
        conexion.rollback()
        print(f"X Error en creación dinámica: {str(e)}")
        raise e
    finally:
        cursor.close()
        conexion.close()