import os
import oracledb
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

def conectar():
    # Usamos el modo "Thin" de oracledb (no requiere Instant Client)
    return oracledb.connect(
        user=os.getenv("ORACLE_USER"),
        password=os.getenv("ORACLE_PASSWORD"),
        dsn=os.getenv("ORACLE_DSN")
    )

def inicializar_bbdd():
    conexion = conectar()
    cursor = conexion.cursor()

    # En Oracle no existe 'IF NOT EXISTS' para tablas directamente.
    # Usamos un bloque PL/SQL para verificar si existe antes de crear.
    try:
        cursor.execute("""
            BEGIN
               EXECUTE IMMEDIATE 'CREATE TABLE documentos (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre_archivo VARCHAR2(255),
                    texto_extraido CLOB,
                    respuesta_claude CLOB,
                    fecha TIMESTAMP
                )';
            EXCEPTION
               WHEN OTHERS THEN
                  IF SQLCODE != -955 THEN
                     RAISE;
                  END IF;
            END;
        """)
        conexion.commit()
    finally:
        cursor.close()
        conexion.close()

def guardar_documento(nombre, texto):
    conexion = conectar()
    cursor = conexion.cursor()
    fecha_actual = datetime.now()

    # En Oracle, los placeholders son :1, :2, etc. o nombres con :nombre
    # Usamos 'RETURNING id INTO :id' para obtener el ID generado
    id_generado = cursor.var(int)
    sql = """
          INSERT INTO documentos (nombre_archivo, texto_extraido, fecha)
          VALUES (:1, :2, :3)
              RETURNING id INTO :4 \
          """

    cursor.execute(sql, (nombre, texto, fecha_actual, id_generado))
    ultimo_id = id_generado.getvalue()[0]

    conexion.commit()
    cursor.close()
    conexion.close()

    return ultimo_id

def actualizar_respuesta_claude(doc_id, respuesta):
    conexion = conectar()
    cursor = conexion.cursor()

    # Importante: En Oracle usamos :nombre o :posicion
    cursor.execute("""
                   UPDATE documentos
                   SET respuesta_claude = :1
                   WHERE id = :2
                   """, (respuesta, doc_id))

    conexion.commit()
    cursor.close()
    conexion.close()